### ISSUE TITLE
Make each paragraph referenceable by anchors

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#17]
For API reviews and for discussions it'd be more convenient to have anchors for direct reference like http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html#CommonErrorObject

**Comment by ePaul** [comment]
If by "paragraph" you mean the individual rules (i.e. the things prefixed by must/should/could), then I agree.

**Comment by fmueller** [comment]
In fact, I mean the rules by this.

**Comment by whiskeysierra** [comment]
Referencing headlines in the github file view directly kind of sucks right now, because we have the must/should/can template things in there. Referencing headlines on the page directly requires to lookup the headline id in the source code, which is unfortunate.

**Comment by whiskeysierra** [comment]
This could help https://github.com/rlmv/gitbook-plugin-anchors

**Comment by ePaul** [comment]
OpenAPI is using `<a name="‹identifier›"></a>` inside their section titles. This works with Github's view (though my Markdown editor doesn't like links to those), though I have no idea if it works with the GitBook's HTML view and/or the PDF generator.

**Comment by whiskeysierra** [comment]
The anchor icons are overlapping the headlines. Locally it looked different :/

**Comment by fmueller** [comment]
Only if i hover over it which is ok (Mac/Chrome).

**Comment by ePaul** [comment]
Yeah, it would be a bit nicer if the icons were moved a bit to the left, but this is not a blocker for me.

**Comment by fmueller** [comment]
Can we close this issue again @whiskeysierra ?

**Comment by whiskeysierra** [comment]
I'm trying to identify the conflicting CSS rule that makes the anchor icon appear so big. Looks like it's this one in `style.css`:

```css
.book .book-body .page-wrapper .page-inner section.normal * {
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    font-size: inherit;
}
```

The one that should win is in `plugin.css` line 14:

```css
a.plugin-anchor span {
    margin-left: -25px;
    font-size: 15px;
}
```
