### ISSUE TITLE
Are additionalProperties subject to property naming rules?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#278]
The [compatibility guidelines](http://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html) contain a small reference to `additionalProperties` with a schema as a value:

> Note that this guideline concentrates on default extensibility and does not exclude the use of `additionalProperties` with a schema as a value, which might be appropriate in some circumstances.

Those are used to represent dynamic key-based data structures, usually referred to as maps, objects or hashes. Do the [property naming rules](http://zalando.github.io/restful-api-guidelines/json-guidelines/JsonGuidelines.html) apply to the keys in those data structures as well?

**Comment by whiskeysierra** [comment]
Our JSON guidelines carefully (?) use the word `property` instead of key. I'd therefore treat an object that was specified using `additionalProperties` as a complex value, but a value nonetheless. In other words clients should not assume the same rules for keys in complex values like that.

What are other opinions on this?

**Comment by ePaul** [comment]
I would say that for maps (i.e. an object with just `additionalProperties` and not directly defined properties), the naming rules don't apply – the keys are not defined in the API definition anyways.

We might need to clarify this in the guidelines.

**Comment by ePaul** [comment]
**From the meeting**:

The JSON guideline about snake_case could get an additional paragraph "this does not apply to maps".

**Comment by wssbck** [comment]
This seems like a very easy way to circumvent any data quality requirements when it comes to JSON data. From the perspective of an API consumer what matters is the data it receives, not whether it was covered with additionalProperties in the schema definition.

**Comment by tkrop** [comment]
Unfortunately, the issue up to now does not reflect the discussion behind this issue, which in my opinion is: **what are the rules for defining property keys/names?**

The reason behind this question is: (1) can generic processing tools can rely on naming conventions of properties, and (2) are special characters are excluded from property names, i.e. is the character restricted to [a-zA-Z0-9_]?

If there is such a rule or understanding implied by the term *snake case*, it is currently very hidden. We should either uncover it, or make clear, that it was never intended to exist.

**Comment by ePaul** [comment]
@wssbck could you elaborate on what kind of "data quality" you are thinking about?

If we have a map with country-codes as keys, a consumer is not served by having them lower-case instead of the natural upper-case.

**Comment by dehora** [comment]
> (1) can generic processing tools can rely on naming conventions of properties,

No, imo. It's too fragile for tools to rely on conventions. Conventions can change.

>  (2) are special characters are excluded from property names, i.e. is the character restricted to [a-zA-Z0-9_]?

I imagine you're referring to this: http://zalando.github.io/restful-api-guidelines/json-guidelines/JsonGuidelines.html#must-property-names-must-be-an-ascii-subset

It's worth noting this is ultimately stylistic and not technical (up to the point where property names allow escaped/unicode chars, then there's a technical element). Nothing really breaks here except people's eyes and hearts. So I think it's reasonable to do this:

1. Scope the above guideline to schema declared properties where the API designer has control of representations.

1. Make `additionalProperties` naming rules a should - as in, if you have a clear reason to break with the guidelines (eg as @ePaul's example, or maybe you're dealing with legacy/external data out of your control, that's ok, otherwise follow the convention).

**Comment by wssbck** [comment]
@ePaul I think I have misread the intent of the disputed part of the guidelines. I thought having certain requirements as to the naming of JSON attributes was a data quality measure. I assumed it was much more than a stylistic suggestion and that it was introduced to ensure clients could rely on certain conventions about the shape of the data returned from APIs.

The wording in the guidelines is strong, using a MUST, hence my interpretation.

Anyway, after reading this discussion I realised my mistake. I would like to ask for a precise clarification in the guidelines, along the lines of what @dehora said.

**Comment by ePaul** [comment]
**From the meeting**

* rule [119](http://zalando.github.io/restful-api-guidelines/#119) should tell a regular expression.
* add example for a map to rule 118 (or as a new rule?)

**Comment by ePaul** [comment]
As there was some confusion, here is an example of a schema definition which is using a map:

```yaml
definitions:
  Message:
    description:
      A message together with translations in several languages.
    type: object
    properties:
      message_key:
        type: string
        description: The message key.
      translations:
        description:
          The translations of this message into several languages.
          The keys are locale identifiers (ISO-639- language codes, together with an optional ISO-3166 country-code, separated by `_`).
        type: object
        additionalProperties:
          type: string
          description: the translation of this message into the language identified by the key.
```
The `translation` property here has a type `Map<String, String>` (in Java speak), and is represented in JSON as an object. The keys are the "property names", but they are not property names in the sense of the guidelines – so the camel-case requirements do not apply, possibly also not the ASCII one –, and my goal for this issue is to make this clear in the guidelines.
