### ISSUE TITLE
Rule on sort conflicts with enum values rule

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#572]
The rule [sort](https://opensource.zalando.com/restful-api-guidelines/#sort) conflicts with the rule of defining [upper snake case enum values](https://opensource.zalando.com/restful-api-guidelines/#240) by suggesting to use the [lower snake case property names](https://opensource.zalando.com/restful-api-guidelines/#118) in conjunction with `+` and `-`.

**Comment by vadeg** [comment]
The may apply to `_embed` parameter [Rule 158: SHOULD allow optional embedding of sub-resources](https://opensource.zalando.com/restful-api-guidelines/index.html#158).

**Comment by ePaul** [comment]
Just to add an example:
```
parameters:
  sort:
   schema:
      type: array
      items:
        type: string
        enum:
         - "+id"
         - "-id"
         - "+name"
         - "-name"
```
