### ISSUE TITLE
How to handle cases where OpenAPI is not enough?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#72]
Related to #11 

Currently we have two actual real world use cases where we use JSON Schema:
- Query API (<del>Shop</del> Search)
- Event Schema Registry (Nakadi)

We should discuss and agree on:
- When is it OK to use JSON Schema?
- What are some known shortcomings of OpenAPI that we know of (e.g. anyOf)?
- How should APIs be documented that use JSON Schema?
- How to embed JSON Schema in OpenAPI?
- How to describe purely event-driven APIs? Sample JSON files + Schema YAML files?

**Comment by whiskeysierra** [comment]
Embedding a JSON schema could look like this:

```yaml
Entity:
  x-schema:
    anyOf:
      - type: string
      - type: object
```
